version: "3"

services:
  #db:
  #  image: postgres:13.3-alpine
  #  environment:
  #    POSTGRES_USER: todoapp
  #    POSTGRES_PASSWORD: password
  #    POSTGRES_DB: todoapp
  #  volumes:
  #    - db_data:/var/lib/postgresql/data/

  web:
    image: sagarparkar/python-todo-app:v4
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - db_data:/app
    ports:
      - "5000:5000"
    #depends_on:
    #  - db

volumes:
  db_data:
