apiVersion: v1
kind: Service
metadata:
  name: my-to-do-service
spec:
  type: NodePort
  selector:
    app: to-do
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5000
      targetPort: 5000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: to-do
spec:
  selector:
    matchLabels:
      app: to-do # has to match .spec.template.metadata.labels
  serviceName: "to-do"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: to-do # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: to-do-app
        image: sagarparkar/python-todo-app:v13
        ports:
        - containerPort: 5000
          name: web
        volumeMounts:
        - name: www
          mountPath: /app/data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/my-pv-vol